FROM ubuntu:{UBUNTU_RELEASE}

RUN apt-get update && apt install -y \
    software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y \
    libc6={LIBC_VERSION} \
    gcc={GCC_VERSION} \
    make \
    gnupg \
    pkg-config \
    wget \
    libxml2-dev \
    swig \
    python3.7-dev \
    perl

WORKDIR /build

ADD resources/build-redland.sh /build

ENTRYPOINT ["/build/build-redland.sh"]
